require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# temporary `DT_TOOLCHAIN_DIR` environment variable
post_install do |installer|
  assertDeploymentTarget(installer)
end

target 'App' do
  capacitor_pods
end
